#!/usr/bin/env bash
#instalation of nginx and header name
sudo apt -y update
sudo apt -y upgrade
sudo apt-get install -y haproxy
sudo sed -i "$ a\ENABLED=1" /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\ \tlisten zandile \n\tmode http\n\tbind *:80\n\tbalance roundrobin\n\tserver 4496-web-02 54.242.100.177:80 check\n\tserver 4496-lb-01 34.229.80.1391:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
